language: java
jdk: openjdk8
branches: 
  - master
  - 1.x
  - 2.x
cache:
  directories:
  - $HOME/.m2
after_success:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
  - $GPG_DIR/publish.sh
env:
  global:
  - GPG_DIR="`pwd`/.travis/deploy"
